---
title: "Exercises | Data Manipulation"
theme : united
author: "EcoHealth Alliance"
output: html_document
highlight: tango
---

### Data structure part 2

1. How many rows are there in the *soil* dataframe? 
2. How many variables does the *soil* dataframe have?  
3. Retrieve the first 6 and last 6 entries of this dataframe.
4. Retrieve the value for the 4th row and 5th column.

### Drop/Add columns

1. Create a new dataframe (DF1) considering only columns 2-5 in *soil*
2. Create a *Site* (select andy location you like) vector with as many elements as rows in the new dataframe. **Hint** : use the *rep*() function. 
3. Attach *Site* to the new dataframe (DF1)

### Change column names

1. Change the following column names in the *soil* dataframe as indicated:
- Org_Matter to OM
- Mic_BiomassC to C_biomass
- Mic_BiomassN to N_biomass

### Subsetting

1. Create a new dataframe (degrade) by subsetting the *soil* dataframe to all *Forest_Type* = **Degraded** 
2. Check the structure of *degrade*. How many factors are in Forest_Type? What must be done to correct this? 
3. Create a new dataframe (acidic) by subsetting *soil* with all *pH* lower than 4.
4. How many observations does *acidic* have? 

### Operations
1. Load the *cancer* dataframe
2. Using the *cancer* dataframe, create a new column (Cdiff) by calculating the total difference in cist numbers(inital to week 4). 
2. Append *Cdiff* to your dataframe. **Hint** use the **$** operator
